import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/navbar/page";
import ContextProvider from "./contextProvider";
import { Toaster } from "react-hot-toast";
import QueryProvider from "./utils/QueryProvide";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Recipe App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <Toaster />
          <Navbar />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
